### ISSUE TITLE
Error attempting to run Cadence docker locally: waiting for cassandra to start up

### ISSUE THREAD

**Issue by ejstembler** [uber/cadence#4216]
**Version of Cadence server, and client(which language)**

- Server version: unknown, whatever is being used in docker image: ubercadence/server:master-auto-setup
- Client version: not applicable
- Client langauge: not applicable
- macOS version: Big Sur, version 11.3.1 (20E241)
- Docker Desktop: 3.3.3 (614133)
  - Engine: 20.10.6
  - Compose: 1.29.1  

**Describe the bug**

Running `docker-compose up` causes an endless loop error of: `waiting for cassandra to start up`

**To Reproduce**
Is the issue reproducible? 
- [Yes]

**Steps to reproduce the behavior:**

Following the instructions from [Getting Started - Run Cadence Server Using Docker Compose](https://cadenceworkflow.io/docs/get-started/installation/#run-cadence-server-using-docker-compose)

Create a directory:

```console
mkdir cadence-getting-started
```

Change to directory:

```console
cd cadence-getting-started
```

Download `docker-compose.yml` file and `prometheus_config.yml` file:

```console
curl -O https://raw.githubusercontent.com/uber/cadence/master/docker/docker-compose.yml && curl -O https://raw.githubusercontent.com/uber/cadence/master/docker/prometheus_config.yml
```

Start Cadence Service:

```console
docker-compose up
```

Output which endlessly loops:

```text
cadence_1        | + echo 'waiting for cassandra to start up'
cadence_1        | + sleep 1
cadence_1        | + cqlsh -u cassandra -p cassandra --cqlversion=3.4.4 cassandra
cadence_1        | Traceback (most recent call last):
cadence_1        |   File "/usr/bin/cqlsh", line 2447, in <module>
cadence_1        |     main(*read_options(sys.argv[1:], os.environ))
cadence_1        |   File "/usr/bin/cqlsh", line 2425, in main
cadence_1        |     encoding=options.encoding)
cadence_1        |   File "/usr/bin/cqlsh", line 473, in __init__
cadence_1        |     load_balancing_policy=WhiteListRoundRobinPolicy([self.hostname]),
cadence_1        |   File "/usr/lib/python2.7/site-packages/cassandra/policies.py", line 426, in __init__
cadence_1        |     for endpoint in socket.getaddrinfo(a, None, socket.AF_UNSPEC, socket.SOCK_STREAM)]
cadence_1        | socket.gaierror: [Errno -2] Name does not resolve
```

**Expected behavior**

Cadence server expected to start.

**Screenshots**

![Screen Shot 2021-05-24 at 3 11 30 PM](https://user-images.githubusercontent.com/45985338/119396064-616a1c80-bca2-11eb-9bca-d34cdae189f2.png)

**Additional context**

**Comment by yycptt** [comment]
Try
```
$ docker-compose rm
$ docker volume prune
$ docker-compose up
```

It works for me when I encountered the issue.

**Comment by ejstembler** [comment]
@yycptt Unfortunately, that did not resolve the issue.

```console
docker-compose rm
Going to remove cadence-getting-started_cadence-web_1, cadence-getting-started_cadence_1, cadence-getting-started_grafana_1, cadence-getting-started_prometheus_1, cadence-getting-started_cassandra_1, cadence-getting-started_node-exporter_1
Are you sure? [yN] y
Removing cadence-getting-started_cadence-web_1   ... done
Removing cadence-getting-started_cadence_1       ... done
Removing cadence-getting-started_grafana_1       ... done
Removing cadence-getting-started_prometheus_1    ... done
Removing cadence-getting-started_cassandra_1     ... done
Removing cadence-getting-started_node-exporter_1 ... done
```
```console
docker volume prune
WARNING! This will remove all local volumes not used by at least one container.
Are you sure you want to continue? [y/N] y
Deleted Volumes:
392c491714297003f68bb996422776c2c4296dbb6baa1b6988576d6fffcb21cf
2477cd82987e9d76109708d4a61c94da9891a90a456ffe8e135e9ce7b8b440a0
b33a9b1a6e1b80ebbfbb6bd41e62324c14daba29e23911eb93ec8a7d21f58993
225fd463043ecb4086e94ef70da490fe27ebd4b189f570a23cb56b8b63e78c50

Total reclaimed space: 400.2kB
```
```console
docker-compose up
Docker Compose is now in the Docker CLI, try `docker compose up`

Creating cadence-getting-started_prometheus_1    ... done
Creating cadence-getting-started_cassandra_1     ... done
Creating cadence-getting-started_node-exporter_1 ... done
Creating cadence-getting-started_cadence_1       ... done
Creating cadence-getting-started_grafana_1       ... done
Creating cadence-getting-started_cadence-web_1   ... done
Attaching to cadence-getting-started_node-exporter_1, cadence-getting-started_cassandra_1, cadence-getting-started_prometheus_1, cadence-getting-started_grafana_1, cadence-getting-started_cadence_1, cadence-getting-started_cadence-web_1
...
cadence_1        | + echo 'waiting for cassandra to start up'
cadence_1        | + sleep 1
cadence_1        | + cqlsh -u cassandra -p cassandra --cqlversion=3.4.4 cassandra
cadence_1        | Traceback (most recent call last):
cadence_1        |   File "/usr/bin/cqlsh", line 2447, in <module>
cadence_1        |     main(*read_options(sys.argv[1:], os.environ))
cadence_1        |   File "/usr/bin/cqlsh", line 2425, in main
cadence_1        |     encoding=options.encoding)
cadence_1        |   File "/usr/bin/cqlsh", line 473, in __init__
cadence_1        |     load_balancing_policy=WhiteListRoundRobinPolicy([self.hostname]),
cadence_1        |   File "/usr/lib/python2.7/site-packages/cassandra/policies.py", line 426, in __init__
cadence_1        |     for endpoint in socket.getaddrinfo(a, None, socket.AF_UNSPEC, socket.SOCK_STREAM)]
cadence_1        | socket.gaierror: [Errno -2] Name does not resolve
cadence_1        | + echo 'waiting for cassandra to start up'
cadence_1        | + sleep 1
cadence_1        | waiting for cassandra to start up
cadence_1        | + cqlsh -u cassandra -p cassandra --cqlversion=3.4.4 cassandra
cadence_1        | Traceback (most recent call last):
cadence_1        |   File "/usr/bin/cqlsh", line 2447, in <module>
cadence_1        |     main(*read_options(sys.argv[1:], os.environ))
cadence_1        |   File "/usr/bin/cqlsh", line 2425, in main
cadence_1        |     encoding=options.encoding)
cadence_1        |   File "/usr/bin/cqlsh", line 473, in __init__
cadence_1        |     load_balancing_policy=WhiteListRoundRobinPolicy([self.hostname]),
cadence_1        |   File "/usr/lib/python2.7/site-packages/cassandra/policies.py", line 426, in __init__
cadence_1        |     for endpoint in socket.getaddrinfo(a, None, socket.AF_UNSPEC, socket.SOCK_STREAM)]
cadence_1        | socket.gaierror: [Errno -2] Name does not resolve
```

**Comment by longquanzheng** [comment]
@ejstembler can you use `docker logs -f docker_cassandra_1` to see the logs of the cassandra container? it's better to see what's going on. If it can't be up, there should be some errors.

**Comment by longquanzheng** [comment]
Also I usually use this prune command to be more aggressively cleanup
```
docker system prune --all
```

**Comment by ejstembler** [comment]
I discovered my issue...

By chance, I decided to check if any ports were being used already:

```console
lsof -i :8080
```

Apparently, last week I was going through the unrelated, [Astronomer quick start](https://www.astronomer.io/docs/cloud/stable/develop/cli-quickstart), and is was still running in the background using port `8080`.

After I killed it, `astro dev stop`, I was able to get past the Cassandra endless loop.

Thanks for everyone's help, @yycptt & @longquanzheng
