### ISSUE TITLE
History  service panic

### ISSUE THREAD

**Issue by mfateev** [uber/cadence#554]
Running on local docker. Getting panic:

```
cadence_1      | time="2018-02-10T20:28:04Z" level=debug msg="Decision Updated: {Schedule: -23, Started: -23, ID: emptyUuid, Timeout: 0, Attempt: 0, Timestamp: 0}" Service=cadence-history execution-id=7f2ca02f-b2a7-4dbc-b5c9-6b05c6143282 run-id=f0d47549-2df0-43f9-8666-681702eea4ad shard-id=2 wf-component=history-cache
cadence_1      | 2018/02/10 20:28:04 Unary handler panicked: runtime error: invalid memory address or nil pointer dereference
cadence_1      | goroutine 21785 [running]:
cadence_1      | runtime/debug.Stack(0xc421126b78, 0xd3e000, 0x1315750)
cadence_1      | 	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
cadence_1      | github.com/uber/cadence/vendor/go.uber.org/yarpc/api/transport.DispatchUnaryHandler.func1(0xc421127b70)
cadence_1      | 	/go/src/github.com/uber/cadence/vendor/go.uber.org/yarpc/api/transport/handler.go:110 +0x6e
cadence_1      | panic(0xd3e000, 0x1315750)
cadence_1      | 	/usr/local/go/src/runtime/panic.go:489 +0x2cf
cadence_1      | github.com/uber/cadence/service/history.(*historyEngineImpl).RespondDecisionTaskCompleted(0xc420576fc0, 0x12ed0c0, 0xc421347680, 0xc420a11440, 0x0, 0x0)
cadence_1      | 	/go/src/github.com/uber/cadence/service/history/historyEngine.go:1080 +0x393f
cadence_1      | github.com/uber/cadence/service/history.(*Handler).RespondDecisionTaskCompleted(0xc4204062d0, 0x12ed0c0, 0xc421347680, 0xc420a11440, 0x0, 0x0)
cadence_1      | 	/go/src/github.com/uber/cadence/service/history/handler.go:400 +0x526
cadence_1      | github.com/uber/cadence/.gen/go/history/historyserviceserver.handler.RespondDecisionTaskCompleted(0x12f3460, 0xc4204062d0, 0x12ed0c0, 0xc421347680, 0xc, 0x0, 0x0, 0x0, 0x0, 0xc420953e60, ...)
cadence_1      | 	/go/src/github.com/uber/cadence/.gen/go/history/historyserviceserver/server.go:545 +0xac
cadence_1      | github.com/uber/cadence/.gen/go/history/historyserviceserver.(handler).RespondDecisionTaskCompleted-fm(0x12ed0c0, 0xc421347680, 0xc, 0x0, 0x0, 0x0, 0x0, 0xc420953e60, 0x1, 0x1, ...)
cadence_1      | 	/go/src/github.com/uber/cadence/.gen/go/history/historyserviceserver/server.go:260 +0x85
cadence_1      | github.com/uber/cadence/vendor/go.uber.org/yarpc/encoding/thrift.thriftUnaryHandler.Handle(0xc4207a9600, 0x12edc00, 0x13433d0, 0xc4203c1100, 0x12ed0c0, 0xc421347680, 0xc4212d8ab0, 0x12ebd00, 0xc4213529c0, 0x0, ...)
cadence_1      | 	/go/src/github.com/uber/cadence/vendor/go.uber.org/yarpc/encoding/thrift/inbound.go:84 +0x357
cadence_1      | github.com/uber/cadence/vendor/go.uber.org/yarpc/encoding/thrift.(*thriftUnaryHandler).Handle(0xc4207a9860, 0x12ed0c0, 0xc421343140, 0xc4212d8ab0, 0x12ebd00, 0xc4213529c0, 0xc42053af00, 0xea6158)
cadence_1      | 	<autogenerated>:8 +0xa6
cadence_1      | github.com/uber/cadence/vendor/go.uber.org/yarpc/internal/observability.(*Middleware).Handle(0xc4202da6c0, 0x12ed0c0, 0xc421343140, 0xc4212d8ab0, 0x12ebf40, 0xc4213802d0, 0x12e4d80, 0xc4207a9860, 0xed2114cf2, 0x332f75d)
cadence_1      | 	/go/src/github.com/uber/cadence/vendor/go.uber.org/yarpc/internal/observability/middleware.go:74 +0x117
cadence_1      | github.com/uber/cadence/vendor/go.uber.org/yarpc/api/middleware.unaryHandlerWithMiddleware.Handle(0x12e4d80, 0xc4207a9860, 0x12e2b00, 0xc4202da6c0, 0x12ed0c0, 0xc421343140, 0xc4212d8ab0, 0x12ebf40, 0xc4213802d0, 0xc420961a88, ...)
cadence_1      | 	/go/src/github.com/uber/cadence/vendor/go.uber.org/yarpc/api/middleware/inbound.go:71 +0x8a
cadence_1      | github.com/uber/cadence/vendor/go.uber.org/yarpc/api/middleware.(*unaryHandlerWithMiddleware).Handle(0xc4207a9a80, 0x12ed0c0, 0xc421343140, 0xc4212d8ab0, 0x12ebf40, 0xc4213802d0, 0x1326240, 0xc4207a9a01)
cadence_1      | 	<autogenerated>:2 +0xa7
cadence_1      | github.com/uber/cadence/vendor/go.uber.org/yarpc/api/transport.DispatchUnaryHandler(0x12ed0c0, 0xc421343140, 0x12e4bc0, 0xc4207a9a80, 0xed2114cd4, 0x342ce5e, 0x1326240, 0xc4212d8ab0, 0x12ebf40, 0xc4213802d0, ...)
cadence_1      | 	/go/src/github.com/uber/cadence/vendor/go.uber.org/yarpc/api/transport/handler.go:115 +0xdb
cadence_1      | github.com/uber/cadence/vendor/go.uber.org/yarpc/transport/tchannel.handler.callHandler(0xc4208f7b30, 0x7efd0e860b48, 0xc42054c630, 0x12ec440, 0x1343020, 0x12ed0c0, 0xc421343140, 0x12f1be0, 0xc42107c3c0, 0xc4213802d0, ...)
cadence_1      | 	/go/src/github.com/uber/cadence/vendor/go.uber.org/yarpc/transport/tchannel/handler.go:182 +0x7fe
cadence_1      | github.com/uber/cadence/vendor/go.uber.org/yarpc/transport/tchannel.handler.handle(0xc4208f7b30, 0x7efd0e860b48, 0xc42054c630, 0x12ec440, 0x1343020, 0x7efd0e860d98, 0xc4208e7f40, 0x12f1be0, 0xc42107c3c0)
cadence_1      | 	/go/src/github.com/uber/cadence/vendor/go.uber.org/yarpc/transport/tchannel/handler.go:97 +0x169
cadence_1      | github.com/uber/cadence/vendor/go.uber.org/yarpc/transport/tchannel.handler.Handle(0xc4208f7b30, 0x7efd0e860b48, 0xc42054c630, 0x12ec440, 0x1343020, 0x7efd0e860d58, 0xc4208e7f40, 0xc42107c3c0)
cadence_1      | 	/go/src/github.com/uber/cadence/vendor/go.uber.org/yarpc/transport/tchannel/handler.go:90 +0xa3
cadence_1      | github.com/uber/cadence/vendor/go.uber.org/yarpc/transport/tchannel.(*handler).Handle(0xc4208f7b60, 0x7efd0e860d58, 0xc4208e7f40, 0xc42107c3c0)
cadence_1      | 	<autogenerated>:34 +0x87
cadence_1      | github.com/uber/cadence/vendor/github.com/uber/tchannel-go.channelHandler.Handle(0xc420566180, 0x7efd0e860d58, 0xc4208e7f40, 0xc42107c3c0)
cadence_1      | 	/go/src/github.com/uber/cadence/vendor/github.com/uber/tchannel-go/handlers.go:126 +0x96
cadence_1      | github.com/uber/cadence/vendor/github.com/uber/tchannel-go.(*Connection).dispatchInbound(0xc420378fc0, 0x8c00000006, 0xc42107c3c0, 0xc420b02240)
cadence_1      | 	/go/src/github.com/uber/cadence/vendor/github.com/uber/tchannel-go/inbound.go:200 +0x3c5
cadence_1      | created by github.com/uber/cadence/vendor/github.com/uber/tchannel-go.(*Connection).handleCallReq
cadence_1      | 	/go/src/github.com/uber/cadence/vendor/github.com/uber/tchannel-go/inbound.go:131 +0x1370
```

The decision task reply that caused the panic:

```
    StartChildWorkflowExecutionDecisionAttributes {
        TaskList = UnitTest;
        WorkflowType = ITestChild::execute;
        WorkflowId = 88be4541-e983-46ef-b9f8-ba08549a6864:1;
        ExecutionStartToCloseTimeoutSeconds = 2;
        TaskStartToCloseTimeoutSeconds = 1;
        Input = ["[Ljava.lang.Object;",["Hello "]]
    },
    FailWorkflowExecutionDecisionAttributes {
        Details = java.lang.NullPointerException
	at com.uber.cadence.internal.dispatcher.SyncDecisionContext.executeChildWorkflow(SyncDecisionContext.java:128)
	at com.uber.cadence.internal.dispatcher.ChildWorkflowInvocationHandler.executeChildWorkflow(ChildWorkflowInvocationHandler.java:94)
	at com.uber.cadence.internal.dispatcher.ChildWorkflowInvocationHandler.invoke(ChildWorkflowInvocationHandler.java:67)
	at com.uber.cadence.workflow.$Proxy12.execute(Unknown Source)
	at com.uber.cadence.workflow.WorkfowTest$TestParentWorkflow.execute(WorkfowTest.java:520)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.uber.cadence.internal.worker.POJOWorkflowImplementationFactory$POJOWorkflowImplementation.execute(POJOWorkflowImplementationFactory.java:156)
	at com.uber.cadence.internal.dispatcher.WorkflowProc.apply(WorkflowProc.java:44)
	at com.uber.cadence.internal.dispatcher.WorkflowThreadInternal$RunnableWrapper.run(WorkflowThreadInternal.java:61)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
;
        Reason = unknown
    }
}

```

**Comment by mfateev** [comment]
The same happens if there is no FailWorkflowExecutionDecisionAttributes:

```
419  decisions                      : Failed taskId=3 decisions={
    StartChildWorkflowExecutionDecisionAttributes {
        WorkflowType = ITestChild::execute;
        ExecutionStartToCloseTimeoutSeconds = 2;
        TaskStartToCloseTimeoutSeconds = 1;
        WorkflowId = dc86b1ab-525c-4259-96e5-f814ac0d6fd7:1;
        TaskList = UnitTest;
        Input = ["[Ljava.lang.Object;",["Hello "]]
    },
    StartChildWorkflowExecutionDecisionAttributes {
        WorkflowType = ITestChild::execute;
        ExecutionStartToCloseTimeoutSeconds = 2;
        TaskStartToCloseTimeoutSeconds = 1;
        WorkflowId = child2;
        TaskList = UnitTest;
        Input = ["[Ljava.lang.Object;",["World!"]]
    }
}
```

**Comment by mfateev** [comment]
Found the bug. Condition at this line should be != instead of ==:

https://github.com/uber/cadence/blob/master/service/history/historyEngine.go#L1078

**Comment by mfateev** [comment]
I'm preparing a fix.

**Comment by mfateev** [comment]
It looks not as straightforward as I initially thought. I couldn't find a domain in mutable state, only domainUUID. So we either need to change all code to allow nil domain for child events, or populate domain on front-end.

**Comment by mfateev** [comment]
Nil childPolicy also crashes the server.

**Comment by samarabbas** [comment]
We have a domain cache which can be used for both domain or domainUUID lookup.  In this case changing the incorrect if condition is enough as domain is optional parameter and is only used for cross domain calls.  
As for the Nil ChildPolicy I'll fix the panic on server but it is a required parameter.  I'll put validation and fail the decision if ChildPolicy is not set.
Let me prepare fix for both issues.

**Comment by mfateev** [comment]
Fixing condition is not enough as code invoked by this method blows up as doing *Domain on nil value.

**Comment by mfateev** [comment]
I don't think childPolicy should be required for child workflows. It should be just inherited. I would also inherit all other parameters. Just make execution timeout up to time when parent times out.

**Comment by samarabbas** [comment]
Yeah I know.  I have all the places fixed.  Will send out PR soon.

**Comment by samarabbas** [comment]
Not sure about inheriting ChildPolicy from parent but updated the validation logic to inherit Tasklist, WorkflowTimeout and DecisionTimeout from parent.  
Let's talk about ChildPolicy on Monday.
